os:
  - linux

language: csharp
sudo: enabled
mono: none
dotnet: none

services:
  - mysql

notifications:
  email: false

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

env:
  global:
    - DEADLINE_RELEASE=false
  matrix:
    - BUILD_TYPE=Debug STRESS_TESTING=false
    - BUILD_TYPE=Release STRESS_TESTING=true

before-install:
  - echo "Adding required APT repositories..."
  - sudo add-apt-repository ppa:ok2cqr/lazarus
  
  - echo "APT https transport package is required for some in-build operations..."
  - sudo apt install apt-transport-https
  
  - echo "Reset MySQL root password:"
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  
install:
  - echo "Importing Microsoft production packages list..."
  - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  
  - echo "Updating APT local cache..."
  - sudo apt update
  
  - echo "Installing .NET Core SDK v2.1 (latest)"
  - sudo apt install dotnet-sdk-2.1
  
  - echo "Restoring NuGet packages..."
  - dotnet nuget locals --clear all
  - dotnet restore
  - echo "Restoring NuGet packages completed!"

script:
  - echo "Publishing SimplePM Server solution..."
  - dotnet publish SimplePM_Server.sln --configuration $BUILD_TYPE --force --output ./Build/ --verbosity minimal

after_script:
  - echo "Server stress-testing coming soon!"

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL
