//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplePM_Server.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimplePM_Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на START TRANSACTION; 
        ///SELECT 
        ///	`spm_problems`.`difficulty`, 
        ///	`spm_problems`.`adaptProgramOutput`, 
        ///	`spm_problems`.`authorSolution`, 
        ///	`spm_problems`.`authorSolutionLanguage`, 
        ///	`spm_submissions`.`submissionId`, 
        ///	`spm_submissions`.`classworkId`, 
        ///	`spm_submissions`.`olympId`, 
        ///	`spm_submissions`.`time`, 
        ///	`spm_submissions`.`codeLang`, 
        ///	`spm_submissions`.`userId`, 
        ///	`spm_submissions`.`problemId`, 
        ///	`spm_submissions`.`testType`, 
        ///	`spm_submissions`.`problemCode`, 
        ///	`spm_submissions`.`customTes [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string submission_query {
            get {
                return ResourceManager.GetString("submission_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE 
        ///	`spm_submissions` 
        ///SET 
        ///	`status` = &apos;ready&apos;, 
        ///	`testType` = @param_testType, 
        ///	`hasError` = @param_hasError, 
        ///	`compiler_text` = @param_compiler_text,
        ///	`errorOutput` = @param_errorOutput, 
        ///	`output` = @param_output, 
        ///	`exitcodes` = @param_exitcodes, 
        ///	`usedProcTime` = @param_usedProcTime, 
        ///	`usedMemory` = @param_usedMemory, 
        ///	`tests_result` = @param_result, 
        ///	`b` = @param_rating 
        ///WHERE 
        ///	`submissionId` = @param_submissionId 
        ///LIMIT 
        ///	1 
        ///;.
        /// </summary>
        internal static string submission_result_query {
            get {
                return ResourceManager.GetString("submission_result_query", resourceCulture);
            }
        }
    }
}
