//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplePM_Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimplePM_Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to █ SimplePM_Server
        ///█ Copyright (C) 2017, Kadirov Yurij. All rights are reserved.
        ///█ Official website: www.sirkadirov.com
        ///█ Support email: admin@sirkadirov.com.
        /// </summary>
        internal static string consoleHeader {
            get {
                return ResourceManager.GetString("consoleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project DefaultTargets = &quot;Compile&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot; &gt;
        ///	
        ///	&lt;PropertyGroup&gt;
        ///		&lt;appname&gt;[SPM|SUBMISSION_FILE_NAME]&lt;/appname&gt;
        ///    &lt;/PropertyGroup&gt;
        ///	
        ///	&lt;ItemGroup&gt;
        ///		&lt;CSFile Include = &quot;[SPM|SUBMISSION_FILE_NAME].cs&quot;/&gt;
        ///		
        ///		&lt;Reference Include=&quot;System.dll&quot;/&gt;
        ///		&lt;Reference Include=&quot;System.Text.dll&quot;/&gt;
        ///		&lt;Reference Include=&quot;System.Collections.dll&quot;/&gt;
        ///	&lt;/ItemGroup&gt;
        ///	
        ///	&lt;Target Name = &quot;Compile&quot;&gt;
        ///		
        ///		&lt;CSC
        ///			Sources = &quot;@(CSFile)&quot;
        ///			OutputAssembly = &quot;$(appname).e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string msbuild_csharp_tpl {
            get {
                return ResourceManager.GetString("msbuild_csharp_tpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimplePM
        ///========
        ///For programming language you selected
        ///there is no need to use compiler!.
        /// </summary>
        internal static string noCompilerRequired {
            get {
                return ResourceManager.GetString("noCompilerRequired", resourceCulture);
            }
        }
    }
}
